TC_ACCOUNT_ID = ''
TC_API_KEY = ''
TC_API_SECRET = ''
BASE_URL = 'https://api.3commas.io'

API_KEY = ''
SECRET_KEY = ''
SUB_ACCOUNT = ''
PAIRS_BLACKLIST = ['DMG-PERP', 'BRZ-PERP', 'PERP/USD', 'SRN-PERP', 'PRIV-PERP']
LTF_DELAY = 60 #seconds between getting latest market data, processing orders.
LTF_INTERVALS = 5 # Delay * Intervals gives us the total time before the first order
LTF_BULL_CHANGE = 2.0
LTF_BEAR_CHANGE = -2.0
MAX_OPEN_POSITIONS = 20
ORDER_VALUE = 10
TAKE_PROFIT = '0.06'
STOP_LOSS = '0.03'
FUNDS_USAGE = 0.9
SWITCH_PERCENT = -7.0
TREND_STRENGTH = 65  #  Percentage of longs vs shorts to consider not trading against a trend.
OPEN_POSITION_PRIORITY = True # True for max open positions, False for order size #not used in 3Commas, atm

#Create Bot Settings
BASE_ORDER_VOLUME = 10 #IN USD
TAKE_PROFIT = 1.5
SAFETY_ORDER_VOLUME = 10
MARTINGALE_VOLUME_COEFFICIENT = 1.0
MARTINGALE_STEP_COEFFICIENT = 1.5
MAX_SAFETY_ORERS = 4
ACTIVE_SAFETY_ORDERS_COUNT = 3
SAFETY_ORDER_STEP_PERCENTAGE = 0.5
LEVERAGE_CUSTOM_VALUE = 1

#Update Bot Settings
UPDATE_BASE_ORDER_VOLUME = 10 #IN USD
UPDATE_TAKE_PROFIT = 1.2
UPDATE_SAFETY_ORDER_VOLUME = 10
UPDATE_MARTINGALE_VOLUME_COEFFICIENT = 1.0
UPDATE_MARTINGALE_STEP_COEFFICIENT = 1.0
UPDATE_MAX_SAFETY_ORERS = 4
UPDATE_ACTIVE_SAFETY_ORDERS_COUNT = 3
UPDATE_SAFETY_ORDER_STEP_PERCENTAGE = 1.25
UPDATE_LEVERAGE_CUSTOM_VALUE = 1
UPDATE_STOP_LOSS_TYPE = 'stop_loss'  # or stop_loss_and_disable_bot
UPDATE_STOP_LOSS_PERCENTAGE = 0
UPDATE_STOP_LOSS_TIMEOUT_ENABLED = False
UPDATE_STOP_LOSS_TIMEOUT_IN_SECONDS = 300
UPDATE_START_ORDER_TYPE = 'market'

